# 

# Lecture 2.1 NumPy 入門 

- ナムパイ

In [1]:
# ライブラリーのインポート
import numpy as np

# numpyの浮動小数点の表示精度
np.set_printoptions(suppress=True, precision=4)

In [2]:
# NumPyのデータ定義

# 1次元配列変数の定義
a = np.array([1, 2, 3, 4, 5, 6, 7])

# 2次元配列変数の定義
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [3]:
# 内容表示

# 1次元配列変数の表示
print(a)

# 2次元配列変数の表示
print(b)

[1 2 3 4 5 6 7]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
# 要素数の確認

# 1次元配列変数の要素数
print(a.shape)

# 2次元配列変数の要素数
print(b.shape)

# len関数の利用
print(len(a))
print(len(b))

(7,)
(4, 3)
7
4


In [6]:
# 特定列の抽出

print(b)

# 0列
c = b[:, 0]
print(c)

# [0, 1]列
d = b[:, :2]
print(d)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  4  7 10]
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]


In [7]:
# reshape関数

l = np.array(range(12))
print(l)

# 3行4列に変換
m = l.reshape((3, 4))
print(m)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
# 統計関数
print(f'もとの変数: {a}')

a_sum = np.sum(a)  # a.sum()
print(f'和: {a_sum}')

a_mean = np.mean(a)  # a.mean()
print(f'平均: {a_mean}')

a_max = np.max(a)  # a.max()
print(f'最大値: {a_max}')

a_min = np.min(a)  # a.min()
print(f'最小値: {a_min}')

もとの変数: [1 2 3 4 5 6 7]
和: 28
平均: 4.0
最大値: 7
最小値: 1


In [12]:
# NumPy変数間の演算

yt = np.array([1, 1, 0, 1, 0, 1, 1, 0, 1, 1])
yp = np.array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1])
print(yt)
print(yp)

[1 1 0 1 0 1 1 0 1 1]
[1 1 0 1 0 1 1 1 1 1]


In [13]:
# 配列の各要素を同時に比較する
w = (yt == yp)
print(w)

[ True  True  True  True  True  True  True False  True  True]


In [14]:
print(w.sum())

9


In [15]:
# ブロードキャスト機能

print(a)
c = (a - np.min(a)) / (np.max(a) - np.min(a))
print(c)

[1 2 3 4 5 6 7]
[0.     0.1667 0.3333 0.5    0.6667 0.8333 1.    ]


In [16]:
print(a.shape)
print(c.shape)

(7,)
(7,)


In [17]:
# 数値配列の生成

x = np.linspace(-5, 5, 11)
print(x)

[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
